export const ModFullNames = {
  NM: "No Mod",
  EZ: "Easy",
  NF: "No Fail",
  HT: "Half Time",
  HR: "Hard Rock",
  SD: "Sudden Death",
  PF: "Perfect",
  DT: "Double Time",
  NC: "Nightcore",
  FI: "Fade In",
  HD: "Hidden",
  FL: "Flashlight",
  SO: "Spun Out",
  TD: "Touch Device",
  MR: "Mirror",
  "4K": "4 Keys",
  "5K": "5 Keys",
  "6K": "6 Keys",
  "7K": "7 Keys",
  "8K": "8 Keys",
  "9K": "9 Keys",
};
